
# https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml

window:
  opacity: .85
  #decorations: none # now to figure out how to move it...
  padding:
    x: 5
    y: 5


font:
  normal:
    #"hasklig medium"
    family: "Meslo LG M" # "Mono" # noto sans mono by default for chromeos
    style: Regular
  size: 10.5

  bold:
    family: "Meslo LG M"
    style: Bold

  italic:
    family: "Meslo LG M"
    style: Italic

  bold_italic:
    family: "Meslo LG M"
    style: Bold Italic


key_bindings:
  - { key: N, mods: Alt, action: CreateNewWindow }
  - { key: N, mods: Control, action: CreateNewWindow }
  #- { key: Space, mods: Shift|Control, mode: ~Search, action: ToggleViMode } # default
  - { key: V, mods: Control, mode: ~Search, action: ToggleViMode }


#draw_bold_text_with_bright_colors: false

#selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false
