# edit config file directly, then backup
# :config-open

# backup
# cp C:\Users\ra\AppData\Roaming\helix\config.toml C:\Users\ra\my-stuff\repos\my-programming-stuff\configs\windows\helix

# TODO: / main things that bother me
# where is the repeat-action? '.' repeats the last paste or something..
# use c+j/k to move down/up pop-up dialog lists
# ISSUE: discuss/ask for a set-opacity/transparency command
#  - seems to be working differently in wezterm, no config necessary!!
# add aura theme
#   - https://github.com/daltonmenezes/aura-theme/issues/202
#   - then can use it as a base to create my own theme


# branches:
# https://github.com/mattwparas/helix/tree/steel-event-system
#   - https://github.com/helix-editor/helix/pull/8675
#   - scheme scripting / "plugin-system"





# default config:
# https://github.com/helix-editor/helix/issues/1210

# started with a copy of this one:
# https://github.com/eichiarakaki/helix/blob/main/config.toml
# also merged in these
# https://github.com/x448/helix-editor-config-toml/blob/main/config.toml
# https://github.com/ravsii/.helix/blob/main/config.toml
# TODO: working on merging this one
# https://gitlab.com/obxhdx/dotfiles/-/blob/main/config/config/helix/config.toml
# TODO: this one looks quite custom..
# it seems very left-handed, motions with left-hand, which frees the right-hand to use mouse/touch-pad/touch-screen?
# but why? it would be one or the other
# https://github.com/clo4/dotfiles/blob/main/dot_config/helix/config.toml

# awesome helix
# https://github.com/rajasegar/awesome-helix?tab=readme-ov-file
#   - also contains many configs to borrow from


# ISSUE:

# known issues:
# TODO: i broke terminal copy/paste (a-c/v)
# why paste is slow:
# https://github.com/helix-editor/helix/issues/1021#issuecomment-963353157
#  - as a work-around, it literally types one character at a time


# my issues:
# https://github.com/helix-editor/helix/pull/9316
#   - about making wren work

# https://github.com/helix-editor/helix/discussions/1172
#   - "option to show the functions being called"
 



# NOTE: press space,? to open the command picker, then can see all of the commands that can be mapped to a key (or macro!)


# structure:
# theme
# [keys]
#  - for quick editing
# [editor]


theme = "boo_berry"
#  - most similar to 'default', with much less contrast and no bold
#  - better than default for code, but i might default more for non-code..

# temp programming themes until aura dark is ported
# theme = "nightfox"
# theme = "tokyonight"


# re-map some keys
# NOTE: only add a new keybinding when you *frequently* perform the actions, not because you think it would be 'nice' or 'useful'
#       though, it's okay to add multiple key-maps of the same action, as there are multiple conventions in my head
# NOTE: use no_op for unmapped keys to be explicit and know what isn't mapped

# https://docs.helix-editor.com/keymap.html
# https://docs.helix-editor.com/remapping.html

# repo files:
# helix-term/src/keymap/default.rs # change the default key-map
# src/commands.rs # add commands to the app here!

# my conventions:
# alt (and alt+shift) is reserved for terminal/tmux commands
#   - (by default, windows terminal used control+shift)
#   - might change once i begin using a tmux (zellij)
# **function key is currently un-mapped**
# - vscode uses it for:
# f1 = "command_pallete" # space,?
# f2 = "rename_symbol" # space,r
# f3 = "search_next" # n
# S-f3 = "search_previous" N (S+n)
# f5,f8-f11 = debugging stuff # space,g
# f12 = "goto_definition" # g,d; A+f12 peek def
  
# control is the main modifier key to use
# control+shift is often used to denote the opposite action as control+key
# control+alt+shift is used in situtations where control+shift is used for a main action, and adding alt does an alt action
# shift also symbolizes extending highlight/selection
# caps-lock is re-mapped to escape on the OS-level
# right-control and right-alt are unused


# see vs-code reference for shortcuts
# https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf


[keys.normal]
# common windows OS shortcuts
# TODO: maybe can use alt for :commands
C-s = ":write" # default was save_selection (to jump-list)
C-a = "select_all" # useful in combination with select_mode
C-S-s = ":write-all"
C-A-s = ":write!"
C-A-S-s = ":write-all!"
C-q = ":quit" # matches the mapping in window-mode
C-S-q = ":quit-all"
C-A-q = ":quit!"
C-A-S-q = ":quit-all!"

# these are also in the space pop-up menu, eventually will wean off of them too, as they go against the default y/p mappings
# TODO: could just use the clipboard only, and avoid using the main register "
# TODO: a lot of these don't work in select-mode, which is what i now often use instead of x :/
# C-c = "yank_joined_to_clipboard" # space,Y, default was toggle_comments
# C-v = "paste_clipboard_before" # space,P
C-y = "yank_joined_to_clipboard" # don't rememeber why.. better formatting for junk copied from the web?..
C-S-y = "yank_to_clipboard" # space-y
C-p = "paste_clipboard_before" # space,P, usually this is the one i want, not p/after
C-S-p = "paste_clipboard_after" # space,p
C-r = "replace_selections_with_clipboard" #space,R, :clipboard-paste-replace?


C-r = ":reload" # Reload the current document from disk
A-f = ":format"

C-S-space = "command_palette" # space-space is nice too, c-s = "completion", TODO: doesn't work in neither windows terminal nor wezterm, i think windows os is using it for something :/ i think it's the same problem for c-space, which i want for "completion"
# C-S-p = "command_palette" # vs-code default


# especially in case the default C-c is mapped to copy
"C-/" = "toggle_comments" # S-/ or ? is mapped to reverse search, which is kinda useless too, as you can press N to go to go up, good for C-like langs
"#" = "toggle_comments" # just an extra binding for an unmapped key, good for ruby-like langs





# sensible defaults
# TODO: change a few defaults that don't make sense

# TODO: testing these
# alt way of inserting before/after
# insert at the cursor
# instead of select -> i/a, ; -> i/a
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]
";" = "flip_selections" # A-;, this key is feels really really good, can use key to map to repeat_last_motion
"C-;" = "collapse_selection"

R = ["collapse_selection", "replace"] # just limit to replacing one char, i mean, how often are you really going to be replacing a selection with one repeating char?.. ascii art?
D = ["collapse_selection", "delete_selection"] # to delete one char, matches R above

# x = "extend_line_below" # the default
# TODO: default X = extend_to_line_bounds now unmapped!
# X = "extend_line_above" 
x = ["extend_line", "select_mode"] # fantastic mapping, teaches you to use select_mode in the process
X = ["extend_line", "select_mode", "flip_selections"] # same as the above but prepare for going up

# x without the newline?
# select within the line bounds, useful for quick whole-line changes
# X = ["goto_first_nonwhitespace", "select_mode", "goto_line_end", "normal_mode"] # TODO: make it extend to next line, like x does
# select_line_below? # how does this work..?
# TODO: C-x - delete/cut line?
# TODO: C-S-x - delete/cut from first non-white-space?


# r<->R: i don't understand the use of r for more than one char, whereas R is used more often, replacing a selection, and works well with search (search and replace); can just use c to replace a single char, at the cost of one more key-press..??
r = "replace_with_yanked" # this matches y/p better
# R = "replace" # NOTE: re-mapped above
# also have space-R and C-r = "replace_selections_with_clipboard"



# TODO: think about basic movements some more
# dfjk for left,right,down,up?
#  - not supposed to use left/right often
# qw for back/forward one word
#  - opens up b for buffer pop-up menu
# ft?
# a-. is strange for repeat last motion... change it back to vi's default ;?
'.' = "repeat_last_motion" # TODO: not working, A-., default was repeat last insert
# 'C-.' = # TODO: repeat_last_insert doesn't exist, sort of an automatic macro recording, but why not just select/paste after insert??
# need this for repeat f/t/m/[/]
#  - need ; to clear selection, which is used often in kakaoune-style always select
# . repeat last insert is kinda wierd too..
#  - save you from copy-paste
# uio for jump-list movement, to match jk
C-u = "save_selection" # defualt was page_up
# ,. for next/previous buffer? TODO: should have many of these key-pairs to cycle next/previous




# return was completely unmapped by default
ret = ["move_line_down", "goto_first_nonwhitespace"]
S-ret = ["move_line_up", "goto_first_nonwhitespace"]
# NOTE: also c+j/k in insert-mode, but use it commonly enough..
C-ret = "add_newline_below" # similar to vs-code
C-S-ret = "add_newline_above"




# extend selection
# shift commonly signifies extend selection
B = "extend_prev_word_start" # or long_word
W = "extend_next_word_start"
E = "extend_next_word_end"
# defaults
# "W" => move_next_long_word_start
# "B" => move_prev_long_word_start
# "E" => move_next_long_word_end

# TODO: change join/keep selection? i rarely use them, and this is an important key
# could do extend to next/previous line (like holding shift and pressing down in gui editors), but i don't think it's too useful
# J default is join_selections (into one line)
# K default is keep_selections (selections matching the regex)
# J = "extend_line_down" # makes sense, but i don't envision using it much..
# K = "extend_line_up"
# K = "extend_next_word" # TODO: possibly one of the most used macros..
# K = "hover" # space,k by default
# NOTE: **possibly my most used macros**, avoid using kill_to_line_end/start, go the kakoune way
H = "extend_to_first_nonwhitespace" # vgh[esc], matches c-h
L = "extend_to_line_end" # vgl[esc], matches c-l

# NOTE: these don't yank TODO: should it?
C-S-h = "kill_to_line_start" # can conflict with buffer shortcuts
C-S-l = "kill_to_line_end"

# still missing extend char..
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"
# END extend selection

minus = "decrement" # only A-minus is mapped to merge_selections, 'minus' not '-', for parsing reasons
'=' = "increment" # = maps to format_selections via LSP

# END sensible defaults


# these are the defaults:
# NOTE: these four are free to map
C-b = "no_op" # "page_up" # in z/view
# C-f = "no_op" # "page_down" # in z/view; mapped to file-picker, similar to old terminal fzf
# "C-u" = "half_page_up" # mapped to save jump point
"C-d" = "no_op" # "half_page_down"

# "C-i" = "jump_forward"
# "C-o" = "jump_backward"


# TODO: C+hjkl vs default g, hjkl; this would save the most used set of modified keys
# NOTE: these don't highlight by default
# TODO: could just try replacing it completely with goto_next/prev_paragraph, or put it on S-j/k
# C-j = "goto_next_paragraph"
# C-j = "goto_prev_paragraph"
C-j = "page_down" # C-f, C-d; NOTE: goto_window_top by default
C-k = ["page_up", "goto_window_top"] # C-b, C-u
C-h = "goto_line_start" # gh # NOTE: does not select by default, use H/L key-maps
C-l = "goto_line_end"  # gl;
# C-h = "move_prev_word_end"
# C-l = "move_next_word_start"

# NOTE: these select/highlight by default
"C-[" = "goto_prev_paragraph"
"C-]" = "goto_next_paragraph"
"C-{" = "goto_prev_function"
"C-}" = "goto_next_function"



# buffer/split/terminal-pane shortcuts

# matches terminal split and nav shortcuts (a-hjkl, a-w)
# TODO: make a pop-up menu, or edit c+w "window" pop-up menu
# use these less often than moving around buffers, so mapped it to an additional modifier key
# TODO: this modifier key combo sucks, and it's important for splitting panes
C-S-A-j = "rotate_view"
C-S-A-k = "rotate_view_reverse"
C-S-A-h = ":hsplit-new"
C-S-A-l = ":vsplit-new"
C-S-A-n = ":hsplit-new"
"C-S-A-;" = ":quit" # closes current view # TODO: not working
C-S-A-w = ":quit" # closes current view


# TODO: still testing/figuring this out..
# C-s used by save
# C-v used by paste
# C-S-s = ":vsplit-new" # s for split, fits c+w, s
# C-S-v = ":vsplit-new" # s for split, fits c+w, s
# C-S-h = ":hsplit-new" # s for split, fits c+w, s
# C-r = ":vsplit-new" # vs vsplit (opens current buffer in the new split)
# C-d = ":hsplit-new"

# buffer shortcuts are missing??
# TODO: **create a buffer pop-up menu**
# can use buffer picker (space,b)
C-S-j = "goto_next_buffer" # gn, :bn TODO: gj/gk
C-S-k = "goto_previous_buffer" # gp, :bp
# TODO: choose between these or kill_to_line_start/end
# C-S-h = ":new" # h is further away/less commonly used command; TODO: add "buffer-new" to repo
# C-S-l = ":buffer-close" # bc; more commonly used than new buffer; l for clear?
C-S-n = ":new" # :n
C-S-w = ":buffer-close" # :bc
'C-S-;' = ":buffer-close" # TODO: not working

C-S-f = "file_picker_in_current_buffer_directory" # alt-f used for terminal find # TODO: add alt+/ key-map for terminal find
C-f = "file_picker" # default: page_down; TODO: how does it differ from F (file_picker_in_current_directory)?


# TODO: bring back the arrow-key buffer shortcuts?
# left = ":buffer-previous"
# right = ":buffer-next"
# up = ":new" # or file picker
# down = ":buffer-close"


# terminal mappings for reference
# i re-mapped the keys to solely use alt
# A-h - split horizontal (down)
# A-l - split vertical (right)
# A-j - goto next pane
# A-k - goto previous pane
# A-w = close pane

# A-left/down/up/right # default for windows terminal

# re-size terminal split/pane
# A-S-hjkl # maybe too much..
# A-arrow-keys # i think i use this in wezterm
# A-S-arrow-keys # default for windows terminal



# END buffer/split/terminal-pane shortcuts


# commonly used commands (including macros!! :o)


# TODO: think of a key to create a pop-up menu for macros
#       currently, m = match pop-up, 

# TODO: move selection up/down (macro)
# alt+up/down in vscode
# C-S-j = "move_line_down" # move_line_down/up doesn't do what you think, it just moves the cursor
# C-S-k = "move_line_up"



[keys.insert]
esc = ["collapse_selection", "normal_mode"] # keeping the selection while inserting is kinda weird..
C-space = "completion"
C-j = "completion" # just need an easier shortcut
C-k = "completion"
# C-S-space = trigger hints
# j = { k = "normal_mode" } # Maps `jk` to quickly exit insert mode, as opposed to esc/caps-lock

C-ret = "add_newline_below" # for consistency 
C-S-ret = "add_newline_above"
# TODO: copy line up/down (macro)
# C-S-j/k
# C-k = "kill_line_to_end" # default
C-h = "goto_first_nonwhitespace" # C-u by default
C-l = "goto_line_end" # delete char by default
C-S-h = "kill_to_line_start"
C-S-l = "kill_to_line_end"
# backspace = "delete_char" # default
# C-d = "delete_char_forward" # default
C-S-D = "delete_char_backward"
# C-w = "delete_word_backward" # default is inverted
C-S-w = "delete_word_forward"
C-b = "delete_word_backward" # an extra key that makes sense
C-backspace = "delete_word_backward"
C-S-backspace = "delete_word_forward"


# https://gitlab.com/obxhdx/dotfiles/-/blob/main/config/config/helix/config.toml
# lots of useful stuff here TODO: map these
# maybe a way to invoke normal-mode shortcuts from insert-mode?
# A-b = ["move_prev_word_start", "collapse_selection"]
# A-f = ["move_next_word_end", "move_char_right"]
# C-b = "move_char_left"
# C-e = "goto_line_end_newline"
# C-f = "move_char_right"


# remove arrow-key training wheels
# create all shortcuts within the main key-pad area
# up = "no_op"
# down = "no_op"
# left = "no_op"
# right = "no_op"
# pageup = "no_op"
# pagedown = "no_op"
# home = "no_op"
# end = "no_op"

# common gui editor key-maps
C-left = "move_prev_word_start"
C-right = "move_next_word_end"


[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"] # keep selection by default

# TODO: is there a way to use normal shortcuts? function key?
h = "extend_to_first_nonwhitespace"
l = "extend_to_line_end"


# pop-up menus

## create new pop-up menus!
[keys.normal."backspace"] # ...i don't think backspace is used by anything by default.. TODO: think of a better shortcut: f-keys?, c-esc/c-s-esc/c-a-esc all used by windows os
o = ":config-open"
r = [":config-reload", ":reload-all"]
l = ":o ~/.config/helix/languages.toml"

# [keys.normal.b] # TODO: b used by back one word


## edit existing pop-up menus
[keys.normal.space]
space = "command_palette" # ? by default
q = ":buffer-close" # or x or d
Q = ":buffer-close!"

[keys.normal.g]
j = "page_down" # strangely simply move up/down one line by default TODO: change in repo
k = ["page_up", "goto_window_top"]
# has n/p = goto next/previous buffer by default

[keys.normal."]"]
"]" = "goto_next_paragraph" # make paragraph the default thing
[keys.normal."["]
"[" = "goto_prev_paragraph" # TODO: standardize 'prev' or 'previous' in the helix repo

[keys.normal.m]
a = "surround_add" # default is s
o = "select_textobject_around" # o for outside; default was a

[keys.select.m]
a = "surround_add" # default is s
o = "select_textobject_around" # o for outside; default was a







[editor]
shell = ["pwsh", "-c"]

line-number = "relative"
# auto-format = "false" # WARNING: "true" by default!


# TODO: testing
completion-trigger-len = 1
cursorline = true
color-modes = true
true-color = true
bufferline = "multiple"

# TODO: hmmm, missing padding config..?
# ISSUE: https://github.com/helix-editor/helix/discussions/11723#
# [editor.padding]

[editor.cursor-shape]
# normal = "block"
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 10 # increase value to reduce forced mid-word wrapping

[editor.statusline]
# text-editor info, interactive stuff
left = ["mode", "selections", "register", "spinner", "diagnostics", "workspace-diagnostics"]

# file-related
center = ["file-name", "read-only-indicator", "file-modification-indicator", "version-control"]

# more file info
right = ["file-encoding", "file-line-ending", "position-percentage"]

separator = "│" # ":<:>:<:>:" 
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
# space = "·"
newline = "↵" # ⏎
tab = "⇥" # →
tabpad = "·" # tabs will look like "→···"
nbsp = "⍽"
            
[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: ▏ ┆ ┊ ⸽ ╎
#skip-levels = 1

[editor.auto-pairs]
# default: (){}[]''""``
# TODO: so do these append or override defaults?
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.file-picker]
hidden = false # note: reads local and global .gitignore files by default
parents = false # rid \. and \..

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
display-inlay-hints = true


