# use the :config-reload command to load changes
# use the :config-open command to come back here

# https://www.youtube.com/watch?v=aiSI6vdZWgE
# a 4 minute video to build this simple config

#theme = ""

[editor]
line-number = "relative" # hmmm, this is interesting..
bufferline = "multiple"
#mouse = false # for hardcore practice

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true



[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # combine all of the escape keys

