
"ui.background" = { fg = "#dbdbdb", bg = "#15141b"}

"ui.linenr" = { fg = "#a394f033"}
"ui.linenr.selected" = { bg = "#2e2b38", modifiers = ["bold"]}

"ui.statusline" = { fg = "#adacae", bg = "#1f1a27"}

"ui.selection" = { bg = "3d375e7f"}
"ui.selection.background" = { fg = "3d375e7f"}

"ui.cursor" = { fg = "#15141b", bg = "#f694ff"}
"ui.cursor.match" = { fg = "#a277ff", modifiers = ["bold"] }

"ui.text" = { fg = "#dbdbdb"}
"ui.text.focus" = { fg = "#dbdbdb", bg = "#29263c" }
"ui.text.inactive" = { fg = "#6d6d6d" }

"ui.virtual.indent-guide" = "#2d2d2d"
"ui.virtual.ruler" = { bg = "#2d2d2d" }
"ui.virtual.whitespace" = { fg = "#2d2d2d" }
"ui.virtual.inlay-hint" = { fg = "#cdccce", bg = "#2e2b38" }
"ui.virtual.jump-label" = { fg = "#f694ff", modifiers = ["bold"] }

"ui.highlight" = { bg = "#2e2b38", modifiers = ["bold"] }

"ui.menu" = { fg = "#cdccce", bg = "#1f1a27"}
"ui.menu.selected" = { fg = "#a277ff", bg = "#2e2b38"}

"ui.popup" = { fg = "#cdccce", bg = "1f1a2#7"}

"ui.window" = { fg = "#54c59f"}

"diagnostic.error" = { underline = { color = "#c55858", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#c7a06f", style = "curl" } }
"diagnostic.info" = { underline = { color = "#6cb2c7", style = "curl" } }
"diagnostic.hint" = { underline = { color = "#6cb2c7", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

error = "#c55858"
warning = "#c7a06f"
info = "#6cb2c7"
hint = "#6cb2c7"

attributes = "#a277ff"
type = "#6cb2c7"

constructor = "#6cb2c7"

constant = "#54c59f"
string = "#54c59f"

comment = {fg = "#6d6d6d", modifiers = [ "italic" ]}

variable = "#dbdbdb"
"variable.builtin" = "#a277ff"
"variable.other" = "#f694ff"

"punctuation.delimeter" = "#f694ff"
"punctuation.special" = "#dbdbdb"

keyword = "#a277ff"
operator = "#a277ff"

function = "#ffca85"
tag = "#a277ff"

markup = "#a277ff"
"markup.heading" = "#c7a06f"
"markup.quote" = "#6d6d6d"
"markup.list" = "#a277ff"
"markup.link.url" = { fg = "#54c59f", modifiers = ["underlined"]}

"diff.plus" = "#54c59f"
"diff.delta" = "#c7a06f"
"diff.minus" = "#c55858"




# https://github.com/daltonmenezes/aura-theme/blob/c607be79c8eeaa5a5d7ac66421f8b5c51d936fe8/src/core/colors/schemes/common.ts


# const commonColors = {
#   accent0: '#0f0f0f',
#   accent1: '#a277ff',
#   accent2: '#61ffca',
#   accent3: '#ffca85',
#   accent4: '#9dff65',
#   accent5: '#ff6767',
#   accent6: '#f694ff',
#   accent7: '#edecee', // foreground
#   accent8: '#6d6d6d', // comments
#   accent31: '#ffca85',
#   accent32: '#82e2ff',
#   accent33: '#24222const commonColors = {
#   accent0: '#0f0f0f',
#   accent1: '#a277ff',
#   accent2: '#61ffca',
#   accent3: '#ffca85',
#   accent4: '#9dff65',
#   accent5: '#ff6767',
#   accent6: '#f694ff',
#   accent7: '#edecee', // foreground
#   accent8: '#6d6d6d', // comments
#   accent31: '#ffca85',
#   accent32: '#82e2ff',
#   accent33: '#24222c',
#   accent34: '#00000000', // fully transparent,
#   accent35: '#525156', // activity bar inactive foreground,
# }

# export const commonUI = {
#   accent9: '#cdccce',
#   accent10: '#adacae',
#   accent13: '#2d2d2d',
#   accent14: '#af8aff7f',
#   accent15: '#4d4d4d',
#   accent16: '#ffffff00',
#   accent17: '#a394f033', // secondary-selection
#   accent18: '#a394f000',
#   accent19: '#3ea7847f',
#   accent20: '#3d375e7f', // primary-selection
#   accent22: '#4d466e',
#   accent23: '#3b334b',
#   accent25: '#49c29a',
#   accent26: '#00d89023',
#   accent27: '#ff474720',
#   accent28: '#121016',
#   accent29: '#000000',
#   accent30: '#2d2b38',
#   accent33: '#2e2b38',
#   accent36: '#a19c77', // debugging background
#   accent37: '#353424', // breakpoint frame highlight
#   accent38: '#29263c', // primary-selection without alpha
#   accent39: '#211D26',
# }c',
#   accent34: '#00000000', // fully transparent,
#   accent35: '#525156', // activity bar inactive foreground,
# }

# i think she used colors from both variations

# dark soft/dim
# Purple	#8464c6	132,100,198	accent1	Primary color	
# Purple	#3d375e7f	61,55,94	accent20	Selections	
# Purple	#29263c	41,38,60	accent38	Selections (without alpha)	
# Green	#54c59f	84,197,159	accent2	Secondary color	
# Orange	#c7a06f	199,160,111	accent3	Tertiary color	
# Pink	#c17ac8	193,122,200	accent6	Quaternary color	
# Blue	#6cb2c7	108,178,199	accent32	Quinary color	
# Red	#c55858	197,88,88	accent5	Senary color	
# White	#bdbdbd	189,189,189	accent7	Foregrounds	
# Gray	#6d6d6d	109,109,109	accent8	Comments	
# Black	#15141b	21,20,27	accent12	Backgrounds

# dark
# Purple	#a277ff	162,119,255	accent1	Primary color	
# Purple	#3d375e7f	61,55,94	accent20	Selections	
# Purple	#29263c	41,38,60	accent38	Selections (without alpha)	
# Green	#61ffca	97,255,202	accent2	Secondary color	
# Orange	#ffca85	255,202,133	accent3	Tertiary color	
# Pink	#f694ff	246,148,255	accent6	Quaternary color	
# Blue	#82e2ff	130,226,255	accent32	Quinary color	
# Red	#ff6767	255,103,103	accent5	Senary color	
# White	#edecee	237,236,238	accent7	Foregrounds	
# Gray	#6d6d6d	109,109,109	accent8	Comments	
# Black	#15141b	21,20,27	accent12	Backgrounds	

# https://github.com/daltonmenezes/aura-theme/tree/c607be79c8eeaa5a5d7ac66421f8b5c51d936fe8/src/core/colors/schemes
# # accent24 soft dark #1f1a27

# TODO: maybe i used some colors from the non-soft variation by accident?.. :/

